### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by hongbo-miao** [stackabletech/hdfs-operator#335]
### Affected version

23.1.0

### Current and expected behavior

I am trying to follow [this guide](https://docs.stackable.tech/home/stable/hdfs/getting_started/index.html) to install HDFS.
 
I succeed installing operators by:

```shell
helm repo add stackable-stable https://repo.stackable.tech/repository/helm-stable/
helm install --wait zookeeper-operator stackable-stable/zookeeper-operator --version 23.1.0
helm install --wait hdfs-operator stackable-stable/hdfs-operator --version 23.1.0
helm install --wait commons-operator stackable-stable/commons-operator --version 23.1.0
helm install --wait secret-operator stackable-stable/secret-operator --version 23.1.0
```

Then when I try to install ZooKeeper cluster by:

```shell
kubectl apply -f zk.yaml
```
```yaml
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: simple-zk
spec:
  image:
    productVersion: 3.8.0
    stackableVersion: 23.1.0
  servers:
    roleGroups:
      default:
        replicas: 1
```

I got error:

```shell
Failed to pull image "docker.stackable.tech/stackable/zookeeper:3.8.0-stackable23.1.0": rpc error: code = NotFound desc = failed to pull and unpack image "docker.stackable.tech/stackable/zookeeper:3.8.0-stackable23.1.0": no match for platform in manifest: not found
```

Any idea, thanks! 😃

It seems `docker.stackable.tech/stackable/zookeeper:3.8.0-stackable23.1.0` does not exist.

### Environment

```
➜ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.2
Kustomize Version: v4.5.7
Server Version: v1.26.1+k3s1
```

**Comment by maltesander** [comment]
Hey,

what platform are you running on (try running e.g. "lscpu")?
We currently only support x86_64 images and have experimental support for ARM in some images.

The image `docker.stackable.tech/stackable/zookeeper:3.8.0-stackable23.1.0` exists https://repo.stackable.tech/#browse/browse:docker:v2%2Fstackable%2Fzookeeper%2Ftags%2F3.8.0-stackable23.1.0 but i think you "want" to select a platform that is not supported.

**Comment by hongbo-miao** [comment]
Hi @maltesander oh yeah I am running on macOS with M1 CPU.

Luckily, all docket images I have used so far support arm64. Or maybe this is a trend as there are more and more arm64 devices (?)

Is it possible to support arm64? Thanks a lot! 😃

If using GitHub action, simply need https://github.com/docker/setup-qemu-action

```yaml
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64,arm64

```
