### ISSUE TITLE
Investigate logging configuration and logging tests

### ISSUE THREAD

**Issue by maltesander** [stackabletech/hdfs-operator#620]
@Jimvin discovered problems with configuring logging.

Configuring logging on role level did not work, role group level worked with the following config:
```
  journalNodes:
    roleGroups:
      default:
        replicas: 3
        config:
          logging:
            enableVectorAgent: true
            containers:
              journalnode:
                loggers:
                  ROOT:
                    level: DEBUG
                console:
                  level: DEBUG
    configOverrides: *configOverrides
```

In the logging tests we use the `hdfs` container https://github.com/stackabletech/hdfs-operator/blob/526f58925ca0ea0f543819f05516d3b70e1e28f3/tests/templates/kuttl/logging/04-install-hdfs-automatic-log.yaml.j2#L31.

Looking at the code, it seems to be `hdfs` as well:
- https://github.com/stackabletech/hdfs-operator/blob/526f58925ca0ea0f543819f05516d3b70e1e28f3/rust/crd/src/lib.rs#L1036
- https://github.com/stackabletech/hdfs-operator/blob/526f58925ca0ea0f543819f05516d3b70e1e28f3/rust/crd/src/lib.rs#L1174
- https://github.com/stackabletech/hdfs-operator/blob/526f58925ca0ea0f543819f05516d3b70e1e28f3/rust/crd/src/lib.rs#L1296
- https://github.com/stackabletech/hdfs-operator/blob/526f58925ca0ea0f543819f05516d3b70e1e28f3/rust/operator-binary/src/product_logging.rs#L156

Not sure how that can work, this needs investigation.
